[advisories]
ignore = [
	"RUSTSEC-2021-0141", # TODO: Use something else or fork dotenv
	"RUSTSEC-2021-0145", # Potential only
	"RUSTSEC-2022-0090", # Only when applying migrations
]

[database]
path = ".cargo/advisory-db" # Path where advisory git repo will be cloned
url = "https://github.com/RustSec/advisory-db.git" # URL to git repo
fetch = true # Perform a `git fetch` before auditing (default: true)
stale = false # Allow stale advisory DB (i.e. no commits for 90 days, default: false)