[package]
name = "ours"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
axum = { version = "0.6", features = ["http2", "tracing"] }
color-eyre = "0.6"
dotenv = "0.15"
eyre = "0.6"
serde = { version = "1.0.164", features = ["derive"] }
tokio = { version = "1.28", features = ["full", "tracing"] }
tower = { version = "0.4", features = ["tracing", "full"] }
tower-http = { version = "0.4", features = ["full"] }
tracing = { version = "0.1", features = ["async-await"] }
tracing-subscriber = "0.3"
tracing-utils = { path = "../../lib/tracing-utils" }
